name: Build and deploy Node.js app to Azure Web App - aicoe-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Archive changed files
        run: |
          $changedFiles = git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
          if ($changedFiles) {
            $changedFiles | Out-File -FilePath changed-files.txt -Encoding utf8
            Compress-Archive -Path (Get-Content changed-files.txt) -DestinationPath node-app.zip
          } else {
            Write-Output "No files changed."
            New-Item -Path node-app.zip -ItemType File
          }
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Extract artifact
        run: |
          unzip node-app.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'aicoe-dev'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C5DB7972298348C5B3DE0CC17CEA461C }}